#!/usr/bin/env python3
"""Run a small STAR vs star-rs performance smoke baseline.

This is intentionally a smoke baseline, not a benchmark suite. It uses the
20-read window-stress fixture that has caught aligner parity regressions and
reports wall time for original STAR and the Rust CLI on the same generated
genome. Run from the repository root after building `target/release/star-rs`.
"""

from __future__ import annotations

import argparse
import pathlib
import shutil
import subprocess
import tempfile
import time


GENOME = """>chr1
TAGGCGTCGATGCCGATCCCACGGATGATAACCGATACTCGACATCCGTCACGACCGGCTGAAATATCAGCATAATGTCGACATCGCCCCGCAACATCAGTATTCCCAGGCTCCCTTGAATCCCCGGCAGTAGAACGAGTGTGTGGTTAGTACGCAAAACTTCGGCGGTAGGATCCACGCGTCACAAGTGACATCCGGCGAAACTACGCTTTAGATGAGTTAGGTGCTAATAACAAGCATTTATCCGCTCTCCCCTACAAAAGCCGCTGTTCTAAGCTTATTAGCTGTACCTGCAGATGCGATGCGCACGAACCGCCGGACTTTTGGATTCTAAAGGTTTATATCATCAGCGCTCGGGTAGCTAGTTCGGCTTATGCTTCGTGCTGACCAATCGACCAAGGCGGGGTAATTGCGACGACCCGCGGAACCACAACTTTACCCTAGACAAGCGGCGCGTAGCGTCCTATCGCCGGGAGTCTAACTCAAATCATATGGCCCATCGCAGTGCGTGAGTTTTATTCAGCCCACCCCAACAAGAGATCGAAATAGTAATCTGTCTCTCTGCTATGATGAGACAATGTCCGTACACTCACTACTTGTTGTACAGTAGATATTCAACCTTAGTGGTTGGTACCTTAGGGTGGGCGAATTTTCTCCGTGTTAAGTACACGACAGTCCGGGTCCTACCCTCATCCTGCGAACCAAGTGGCTATCTCACCGAAGCGCTAGGTGAGAGCAACCGGTTAAAAGCTGAACGCCTCTGCTGCGCTTTGCTACTCAGGTAGTGTAGGCAAGCCCGTATAGTATAACACGACCCATCGTGAAGGTAGACGGAGGATTTAAAATGAGTAGTAGAGACTAGGGGATCATGCAACGTATTGAAAAACCACCCGGACATGA
>chr2
TCGTCTACTTGTCTGGTTAAGAGGGCTTGATGGTAGTGCGCCCGAGCCTCGATGAATTACGCGCGCTCAGAACCAACGGAAAGTCTGTTGTCCATTGTTAAGGGACTTTCAAGTTTCCGTGATAGACTAGCGCAAGGCTAGGCCGTCGGCATAAACGTGGGATTCCCGACGTTAACAGTACTAAACATAGGAGACAATTCAATATGGCATGTATAGCGACTCATGGTTGGCACCGGACCGTCTGAAAATGATGACATGAAGACCGCTATCCGACTCCCCATCTCCAATGGCCCTTGTGTAGGCGCGTCTACGCCCTAGACGCTGTAGTTCTGTAAAAGCAGATCAACCTCCGGCAAGCTGTCCATGCTTGCCTGTGAGCGAAATGCAACTTTAGACGCTTCGGTAGAGATTCCGAGAGCGAGAGGTGATAAGTAAATTGCTCTGCTGATAAGTCAAGCAGTATTTTATCAGCACGTTATTATATCATCCTAGTAAATGGAGCGGGCCAGTTAGCGTCGCAGATAGCAGAACATAACTTGGATAGAAGTGCTGCGTCGCGACGGGGGTGTGAATGTGCCGTACTTCCTCTGACAATGGTAGTTCGACGTGCCCTGAGATATAGAATATAAGTTTCCCGTGCAACTAACGGAACCGAGAGAGAAAGTTAAAATGGGCCGTGCAGGCATAGTATTGGCGGGAC
"""

READS = """@r0_36
AGAAGTGCTGCGTCGCGACCGGGGTGTGAATGTGAC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r1_36
AAGAGGGCTTGATGGTAGTGCGCCCGAGCCTCGATG
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r2_30
AGGCGCGTCTACGCCCTAGACGCTGTAGTT
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r3_75
TCTACGCCCTAGACGCTGTAGTTCTGTAAAAGCAGATCAACCTCCGGCACGCTGTCCATGCTTGCCTGTGAGCGA
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r4_75
CTAATAACAAGCATTTATCCGCTCTCCCCTACACAAGCCGCTGTTCTAAGCTTATTAGTTGTACCTGCAGATGCG
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r5_75
GTAGAGATTCCGAGAGCAAGAGGTGATCGGTAAATTGCTCTGCTGATAAGTCAAGGAGTATTTTATCAGCACGTT
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r6_60
GATGCGCACGAACCGCTGGACTTTTGGATTCTAAAGGTTTATATAATCAGCGCTCGGGTA
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r7_30
AGTTCGGCATATGCTTCGTGCTGACCAATC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r8_30
GATCAACCTCCGGCAAGCTCTCCATGCTTG
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r9_30
TGGTAATTGCGACGACCCGCGGAACCACAA
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r10_45
CCTGCGAAACTACGCTTTAGATGAGTTAGGTGCTAATGACAAGCA
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r11_75
CGGACTTTTGGATTCTAAAGGTTTATATCATCGGCGCTCGAGTAGCTAGTTCGGCTTATGCTTCGTGCTGACCAA
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r12_30
TCGCAGATAGCAGAACATAACTTGGATAGA
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r13_30
ATGGCCCATCGCAGTGCGTGAGTTTTATTG
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r14_30
ATTCTAAAGGTTTATATCATCAGCGCTCGA
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r15_60
CTAGTTCGGCTTATGCTTCGGGCTGACCAATCGACCAAGGCGGGGTATTTGCAACGAACC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r16_45
CAACCTACGGCAAGCTGTCCATGCTTGCCTGTGAGCGAAATGCAC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r17_45
CGGACCGTCTGAAAATGATGACATGAAGACCGCTATCCGACTCCC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r18_75
GCTTTAGATGAGTTGGGTGCTATTAACAAGCATTTATCCGCTCTCCCCTACAAAAGCCGCTGTTCTAAGCTTATT
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@r19_30
CGCCCCGCAACATCAGTATTCTCAGGCTCC
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
"""


def timed(cmd: list[str]) -> float:
    start = time.perf_counter()
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return time.perf_counter() - start


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--star", default="STAR/bin/Linux_x86_64_static/STAR")
    parser.add_argument("--star-rs", default="target/release/star-rs")
    parser.add_argument("--keep", action="store_true")
    args = parser.parse_args()

    root = pathlib.Path.cwd()
    star = root / args.star
    star_rs = root / args.star_rs
    if not star.exists():
        raise SystemExit(f"missing original STAR binary: {star}")
    if not star_rs.exists():
        raise SystemExit(f"missing Rust release binary: {star_rs}; run cargo build --release")

    work = pathlib.Path(tempfile.mkdtemp(prefix="star_rs_perf_"))
    try:
        fasta = work / "genome.fa"
        reads = work / "reads.fq"
        genome = work / "genome"
        fasta.write_text(GENOME)
        reads.write_text(READS)
        genome.mkdir()

        timed(
            [
                str(star),
                "--runMode",
                "genomeGenerate",
                "--genomeDir",
                str(genome),
                "--genomeFastaFiles",
                str(fasta),
                "--genomeSAindexNbases",
                "3",
                "--genomeChrBinNbits",
                "5",
                "--limitGenomeGenerateRAM",
                "1000000",
            ]
        )
        common = [
            "--genomeDir",
            str(genome),
            "--readFilesIn",
            str(reads),
            "--outSAMtype",
            "SAM",
            "--seedSplitMin",
            "12",
            "--seedMapMin",
            "5",
            "--outFilterMatchNmin",
            "0",
            "--outFilterScoreMin",
            "0",
            "--outFilterMultimapNmax",
            "20",
            "--outSAMmultNmax",
            "20",
        ]
        cpp_time = timed([str(star), *common, "--outFileNamePrefix", str(work / "cpp/")])
        rust_time = timed([str(star_rs), *common, "--outFileNamePrefix", str(work / "rust/")])
        print(f"original_star_seconds\t{cpp_time:.6f}")
        print(f"star_rs_seconds\t{rust_time:.6f}")
        print(f"ratio_star_rs_over_original\t{rust_time / cpp_time:.3f}")
        print(f"work_dir\t{work if args.keep else '<removed; rerun with --keep to inspect>'}")
    finally:
        if not args.keep:
            shutil.rmtree(work, ignore_errors=True)


if __name__ == "__main__":
    main()
