#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(unused_imports)]

use crate::*;

#[doc = "Original class `Parameters` at STAR/source/ParametersChimeric.h:6."]
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Parameters {
    pub command_line_full: String,
    pub command_line: String,
    pub version_genome: String,
    pub out_file_tmp: String,
    pub run_thread_n: i32,
    pub run_rng_seed: i32,
    pub run_dir_perm: u32,
    pub out_file_name_prefix: String,
    pub out_tmp_keep: String,
    pub run_restart_type: i32,
    pub read_nmates: u32,
    pub read_nends: u32,
    pub read_quality_score_base: u8,
    pub out_std: String,
    pub p_ge: ParametersGenome,
    pub p_ch: ParametersChimeric,
    pub input_bam_file: String,
    pub bam_remove_duplicates_type: String,
    pub bam_remove_duplicates_yes: bool,
    pub bam_remove_duplicates_mark_multi: bool,
    pub bam_remove_duplicates_mate2bases_n: u32,
    pub out_bam_unsorted: bool,
    pub out_bam_coord: bool,
    pub out_bam_compression: i32,
    pub out_sam_bool: bool,
    pub out_wig_references_prefix: String,
    pub out_wig_flags: OutWigFlags,
    pub out_sam_type: Vec<String>,
    pub out_sam_header_hd: Vec<String>,
    pub out_sam_header_pg: Vec<String>,
    pub out_sam_header_comment_file: String,
    pub out_sam_attr_rgline_split: Vec<String>,
    pub quant_tr_sam_yes: bool,
    pub quant_tr_sam_bam_yes: bool,
    pub sam_header_hd: String,
    pub sam_header: String,
    pub sam_header_sorted_coord: String,
    pub out_sam_contents: String,
    pub out_bam_unsorted_header: Vec<u8>,
    pub out_quant_bam_header: Vec<u8>,
    pub p_solo: ParametersSolo,
    pub sj_all: [Vec<u64>; 2],
    pub genome_dir: String,
    pub out_sam_attr_nm_present: bool,
    pub out_sam_attr_order: Vec<i32>,
    pub out_sam_attr_order_quant: Vec<i32>,
    pub out_sam_attributes: Vec<String>,
    pub out_sam_attr_present: SamAttrPresent,
    pub out_sam_attr_present_quant: SamAttrPresent,
    pub out_sam_attr_rgline: Vec<String>,
    pub out_sam_attr_rg: Vec<String>,
    pub out_sam_strand_field_type: i32,
    pub out_sam_mapq_unique: i32,
    pub out_sam_tlen: i32,
    pub out_sam_flag_or: u16,
    pub out_sam_flag_and: u16,
    pub out_sam_attr_ih_start: u32,
    pub out_sam_mode: String,
    pub out_sam_order: String,
    pub out_sam_read_id: String,
    pub out_sam_read_id_number: bool,
    pub out_sam_unmapped_keep_pairs: bool,
    pub out_sam_unmapped_within: bool,
    pub out_sam_filter_yes: bool,
    pub out_sam_filter_keep_only_added_references: bool,
    pub out_sam_filter_keep_all_added_references: bool,
    pub out_sam_mult_nmax: u64,
    pub out_filter_multimap_score_range: i32,
    pub out_filter_multimap_nmax: u64,
    pub out_filter_mismatch_nmax: u32,
    pub out_filter_mismatch_nover_read_lmax: f64,
    pub out_filter_score_min: i32,
    pub out_filter_score_min_over_lread: f64,
    pub out_filter_match_nmin: u32,
    pub out_filter_match_nmin_over_lread: f64,
    pub seed_search_lmax: u32,
    pub seed_search_start_lmax: u32,
    pub seed_search_start_lmax_over_lread: f64,
    pub seed_split_min: u32,
    pub seed_map_min: u32,
    pub out_multimapper_order_random: bool,
    pub out_sam_mult_nmax_is_limited: bool,
    pub out_sam_primary_flag: String,
    pub align_ends_protrude_concordant_pair: bool,
    pub align_ends_type: AlignEndsType,
    pub align_ends_protrude: AlignEndsProtrude,
    pub align_insertion_flush: AlignInsertionFlush,
    pub align_soft_clip_at_reference_ends_yes: bool,
    pub align_sj_overhang_min: u32,
    pub align_sjdb_overhang_min: u32,
    pub align_spliced_mate_map_lmin: u32,
    pub align_spliced_mate_map_lmin_over_lmate: f64,
    pub align_intron_max: u32,
    pub align_intron_min: u32,
    pub align_mates_gap_max: u32,
    pub align_sj_stitch_mismatch_nmax: Vec<i32>,
    pub out_filter_intron_strands: String,
    pub out_filter_intron_motifs: String,
    pub score_genomic_length_log2scale: f64,
    pub score_gap: i32,
    pub score_gap_noncan: i32,
    pub score_gap_gcag: i32,
    pub score_gap_atac: i32,
    pub score_del_base: i32,
    pub score_del_open: i32,
    pub score_ins_base: i32,
    pub score_ins_open: i32,
    pub score_stitch_sj_shift: i32,
    pub read_files_type: Vec<String>,
    pub read_files_type_n: i32,
    pub read_files_prefix: String,
    pub read_files_prefix_final: String,
    pub read_files_names: Vec<Vec<String>>,
    pub read_files_n: u32,
    pub read_files_manifest: Vec<String>,
    pub read_files_command: Vec<String>,
    pub read_files_command_string: String,
    pub read_files_sam_attr_keep_in: Vec<String>,
    pub read_files_sam_attr_keep_all: bool,
    pub read_files_sam_attr_keep_none: bool,
    pub read_files_sam_attr_keep: std::collections::BTreeSet<u16>,
    pub read_files_in_tmp: Vec<String>,
    pub read_files_index: u32,
    pub read_mates_lengths_in: String,
    pub sys_shell: String,
    pub read_name_separator_char: Vec<char>,
    pub out_qs_conversion_add: i32,
    pub var_yes: bool,
    pub wasp_yes: bool,
    pub quant_ge_count_yes: bool,
    pub quant_gene_yes: bool,
    pub quant_gene_full_yes: bool,
    pub quant_gene_full_exon_over_intron_yes: bool,
    pub quant_gene_full_ex50p_as_yes: bool,
    pub quant_yes: bool,
    pub quant_tr_sam_indel: bool,
    pub quant_tr_sam_single_end: bool,
    pub quant_tr_sam_soft_clip: bool,
    pub pe_overlap_nbases_min: u32,
    pub pe_overlap_mmp: f64,
    pub out_filter_mismatch_nover_lmax: f64,
    pub seed_multimap_nmax: u32,
    pub seed_per_read_nmax: u32,
    pub win_bin_chr_nbits: u32,
    pub win_bin_nbits: u32,
    pub win_anchor_dist_nbins: u32,
    pub win_anchor_multimap_nmax: u32,
    pub win_flank_nbins: u32,
    pub win_bin_n: u32,
    pub align_windows_per_read_nmax: u32,
    pub genome_insert_chr_ind_first: u32,
    pub out_bam_sorting_thread_n: u32,
    pub out_bam_sorting_thread_nactual: u32,
    pub out_bam_sorting_bins_n: u32,
    pub out_bam_coord_nbins: u32,
    pub chunk_out_bam_size_bytes: u64,
    pub limit_out_sam_one_read_bytes: u64,
    pub limit_out_sj_one_read: u64,
    pub limit_sjdb_insert_nsj: u32,
    pub out_bam_sorting_bin_start: Vec<u64>,
    pub bam_sorting_log: String,
    pub limit_bam_sort_ram: u64,
    pub limit_genome_generate_ram: u64,
    pub limit_nreads_soft: u64,
    pub out_bam_sort_tmp_dir: String,
    pub out_bam_file_coord_name: String,
    pub chunk_in_size_bytes_array: u64,
    pub chunk_in_size_bytes: u64,
    pub i_read_all: u64,
    pub read_map_number: u64,
    pub align_transcripts_per_read_nmax: u32,
    pub align_transcripts_per_window_nmax: u32,
    pub max_nsplit: u32,
    pub seed_per_window_nmax: u32,
    pub seed_none_loci_per_window: u32,
    pub win_read_coverage_relative_min: f64,
    pub win_read_coverage_bases_min: u32,
    pub p_clip: ParametersClip,
    pub sam_header_extra: String,
    pub read_in_0: String,
    pub read_in_0_pos: usize,
    pub read_files_in: Vec<String>,
    pub read_in_open: Vec<bool>,
    pub read_files_command_pid: Vec<i32>,
    pub two_pass_yes: bool,
    pub two_pass_pass2: bool,
    pub two_pass_pass1sj_file: String,
    pub two_pass_dir: String,
    pub two_pass_pass1reads_n: u64,
    pub run_mode_in: Vec<String>,
    pub genome_num_to_nt: Vec<u8>,
    pub limit_out_sj_collapsed: u64,
    pub out_filter_by_sjout_stage: i32,
    pub out_filter_type: String,
    pub out_sj: bool,
    pub out_sj_filter_reads: String,
    pub out_reads_unmapped: String,
    pub out_sjfilter_count_unique_min: Vec<i32>,
    pub out_sjfilter_count_total_min: Vec<i32>,
    pub out_sjfilter_overhang_min: Vec<i32>,
    pub out_sjfilter_intron_max_vs_read_n: Vec<u32>,
    pub out_sjfilter_dist_to_other_sj_min: Vec<i32>,
    pub sj_novel_n: u32,
    pub sj_novel_start: Vec<u64>,
    pub sj_novel_end: Vec<u64>,
    pub sjdb_insert_yes: bool,
    pub sjdb_insert_out_dir: String,
    pub wasp_output_mode: String,
    pub wasp_sam_tag: bool,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct OutputSjResult {
    pub sj_out_tab: String,
    pub sj_start_gap_tsv: String,
    pub log_main: String,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct AlignEndsType {
    pub in_: String,
    pub ext: [[bool; 2]; 2],
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct AlignEndsProtrude {
    pub in_: Vec<String>,
    pub n_bases_max: i32,
    pub concordant_pair: bool,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct AlignInsertionFlush {
    pub in_: String,
    pub flush_right: bool,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct OpenReadsFilesResult {
    pub opened_inputs: Vec<String>,
    pub read_files_in_tmp: Vec<String>,
    pub reads_command_file_names: Vec<String>,
    pub reads_command_file_contents: Vec<String>,
    pub command_pids: Vec<i32>,
    pub log_main: String,
    pub sam_header_commands: Vec<String>,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct SjdbPrepareResult {
    pub gsj: Vec<u8>,
    pub sjdb_info_txt: String,
    pub sjdb_list_out_tab: String,
    pub log_main: String,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct SjdbBuildIndexResult {
    pub log_main: String,
    pub n_gsj: u32,
    pub sj_new: u64,
    pub n_ind: u32,
    pub ind_array: Vec<[u64; 2]>,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct SjdbInsertJunctionsResult {
    pub log_main: String,
    pub sjdb_prepare: SjdbPrepareResult,
    pub sjdb_build_index: SjdbBuildIndexResult,
    pub gtf: Option<GtfTranscriptGeneSjOutput>,
    pub files_written: Vec<String>,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct GenomeTransformGenomeResult {
    pub log_main: String,
    pub transform_blocks_tsv: String,
    pub debug: String,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct GenomeGenerateResult {
    pub log_main: String,
    pub log_stdout: String,
    pub files_written: Vec<String>,
    pub gtf: Option<GtfTranscriptGeneSjOutput>,
    pub super_transcriptome: Option<GtfSuperTranscriptOutput>,
    pub sjdb_insert: Option<SjdbInsertJunctionsResult>,
    pub n_genome_true: u64,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct GenomeLoadResult {
    pub log_stdout: String,
    pub log_main: String,
    pub load_and_exit: bool,
    pub removed_shared_memory: bool,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct TwoPassRunPass1Result {
    pub log_progress: String,
    pub log_stdout: String,
    pub log_main: String,
    pub pass1_parameters: Parameters,
    pub pass1_chunks: Vec<ReadAlignChunk>,
    pub output_sj: OutputSjResult,
    pub sjdb_insert: Option<SjdbInsertJunctionsResult>,
    pub log_final_out: String,
    pub killed_read_command_pids: Vec<i32>,
    pub reopened_reads: OpenReadsFilesResult,
    pub pass1_sj_file: String,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct StarMainResult {
    pub exit_code: i32,
    pub usage: String,
    pub log_stdout: String,
    pub log_main: String,
    pub log_progress: String,
    pub log_final_out: String,
    pub parameters: Parameters,
    pub genome: Option<Genome>,
    pub genome_generate: Vec<GenomeGenerateResult>,
    pub sjdb_insert: Option<SjdbInsertJunctionsResult>,
    pub two_pass: Option<TwoPassRunPass1Result>,
    pub output_sj: Option<OutputSjResult>,
    pub bam_sort: Option<BamSortByCoordinateResult>,
    pub signal: Option<SignalFromBamResult>,
    pub processed_bam_output: Vec<u8>,
    pub solo_cell_filtering: Option<SoloConstructorCellFilteringResult>,
    pub solo_process_and_output: Option<SoloProcessAndOutputResult>,
    pub transcriptome: Option<Transcriptome>,
    pub stats_all: Stats,
    pub read_chunks: Vec<ReadAlignChunk>,
    pub process_chunks: Vec<ReadAlignChunkProcessChunksResult>,
    pub killed_read_command_pids: Vec<i32>,
    pub removed_tmp: bool,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct OutWigFlags {
    pub yes: bool,
    pub strand: bool,
    pub type_: i32,
    pub format: i32,
    pub norm: i32,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct SignalFromBamRecord {
    pub tid: i32,
    pub pos: u32,
    pub flag: u16,
    pub cigar: Vec<u32>,
    pub nh: Option<u32>,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct SignalFromBamResult {
    pub files: std::collections::BTreeMap<String, String>,
    pub n_unique: f64,
    pub n_multiple: f64,
}

#[doc = "Original class `ParametersChimeric` at STAR/source/ParametersChimeric.h:8."]
#[derive(Clone, Debug, Default, PartialEq)]
pub struct ParametersChimeric {
    pub segment_min: u64,
    pub junction_overhang_min: u64,
    pub segment_read_gap_max: u64,
    pub score_min: i32,
    pub score_drop_max: i32,
    pub score_separation: i32,
    pub score_junction_non_gtag: i32,
    pub main_segment_mult_nmax: u32,
    pub multimap_score_range: u64,
    pub multimap_nmax: u64,
    pub nonchim_score_drop_min: u64,
    pub out_type: Vec<String>,
    pub out_bam: bool,
    pub out_junctions: bool,
    pub out_sam_old: bool,
    pub out_bam_hard_clip: bool,
    pub out_junction_format: Vec<i32>,
    pub filter_string_in: Vec<String>,
    pub filter_genomic_n: bool,
    pub out_chim_sam_opened: bool,
    pub out_chim_sam_contents: String,
    pub out_chim_junction_opened: bool,
    pub out_chim_junction_contents: String,
    pub log_main: String,
}
